import {
  SkillRunnerService,
  type SkillRunnerInvocation,
  type SkillRunnerResult
} from "../../../app/main/domains/execution/skill-runner.service";
import type { StrategyBundle } from "../../../app/shared/types/strategy";

export function createStrategyBundleFixture(): StrategyBundle {
  return {
    profile: {
      id: "profile_active",
      name: "Philippe",
      positioning: "Consultant IA generative pour PME",
      bio: "J aide les PME a deployer l IA sans theatre ni promesse vide.",
      expertiseSummary: "Adoption IA, cadrage, ROI, gouvernance et execution terrain."
    },
    offers: [
      {
        id: "offer_1",
        name: "Audit IA PME",
        promise: "Prioriser les cas d usage utiles et deployables sans theatre.",
        problems: "Trop d idees, pas de priorisation, pas de sponsor, pas de garde-fous.",
        proofPoints: "",
        ctaModes: ""
      }
    ],
    icps: [
      {
        id: "icp_1",
        segment: "Dirigeants de PME",
        pains: "Trop d idees IA, pas assez de priorisation ni de ROI lisible.",
        objections: "Peur du cout, du flou et de la complexite.",
        desiredOutcomes: "Des cas d usage utiles, pilotables et rentables.",
        languageCues: "Deployable, ROI, concret, equipe, pilotage.",
        linkedinBehavior: "Lit des retours terrain et des arbitrages concrets."
      }
    ],
    pillars: [
      {
        id: "pillar_1",
        label: "Methodes",
        description: "Comment cadrer un projet IA sans theatre ni promesse vide.",
        position: 0,
        isDefault: true
      },
      {
        id: "pillar_2",
        label: "ROI",
        description: "Comment arbitrer entre promesse, cout, risque et impact operationnel.",
        position: 1,
        isDefault: false
      },
      {
        id: "pillar_3",
        label: "Adoption IA",
        description: "Comment deployer l IA avec roles, process et responsabilites claires.",
        position: 2,
        isDefault: false
      }
    ],
    voiceRules: [
      {
        id: "rule_1",
        category: "Anti-style",
        ruleText: "Pas de hype, pas de jargon, pas de formule creuse.",
        ruleType: "anti_style",
        createdAt: new Date().toISOString()
      }
    ]
  };
}

function executeFakeCodex(invocation: SkillRunnerInvocation): SkillRunnerResult {
  switch (invocation.skillName) {
    case "linkedin-structure-selector":
      return {
        status: "succeeded",
        summary: "Structure selected by Codex",
        data: {
          hooks: [],
          structure: {
            key: "belief-terrain-reality",
            label: "Croyance -> terrain -> realite",
            rationale: "Comparer la croyance marquee au terrain reel avant de poser une conclusion actionnable."
          },
          variants: [],
          qualitySignals: {
            clarity: 0.82,
            specificity: 0.8,
            antiHypeAlignment: 0.95
          }
        }
      };
    case "linkedin-hook-engine":
      return {
        status: "succeeded",
        summary: "Hooks generated by Codex",
        data: {
          hooks: [
            {
              family: "contrastive",
              text: "Le vrai probleme avec ce sujet, ce n'est pas l'outil.",
              score: 0.83
            },
            {
              family: "diagnostic",
              text: "Si ca bloque, regarde d'abord le process.",
              score: 0.78
            }
          ],
          variants: [],
          qualitySignals: {
            clarity: 0.8,
            specificity: 0.78,
            antiHypeAlignment: 0.95
          }
        }
      };
    case "linkedin-post-writer":
      return {
        status: "succeeded",
        summary: "Draft generated by Codex",
        data: {
          draft: {
            headline: String(invocation.payload.title),
            bodyMarkdown: [
              String(invocation.payload.selectedHook ?? "Le vrai sujet n'est pas l'outil."),
              "",
              String(invocation.payload.angle ?? "Le blocage vient du cadrage."),
              "",
              "En PME, l'automatisation gagne quand il faut fiabiliser un process simple a faible risque.",
              "",
              "Les agents valent le coup seulement quand l'equipe sait deja cadrer, superviser et absorber la complexite supplementaire."
            ].join("\n")
          },
          hooks: (invocation.payload.hooks as Array<{ family: string; text: string; score: number }>) ?? [],
          variants: [],
          qualitySignals: {
            clarity: 0.76,
            specificity: 0.72,
            antiHypeAlignment: 0.95
          }
        }
      };
    case "linkedin-post-editor":
      return {
        status: "succeeded",
        summary: "Draft corrected by Codex",
        data: {
          draft: {
            headline: String(invocation.payload.headline ?? "Draft"),
            bodyMarkdown: `${String(invocation.payload.bodyMarkdown).trim()}\n\nEn pratique, commence par ce que ton equipe saura piloter sans theater ni dette de complexite.`
          },
          hooks: [],
          variants: [],
          qualitySignals: {
            clarity: 0.83,
            specificity: 0.79,
            antiHypeAlignment: 0.96
          }
        }
      };
    case "linkedin-repurpose":
      return {
        status: "succeeded",
        summary: "Variant created by Codex",
        data: {
          draft: {
            headline: `Variante - ${String(invocation.payload.headline)}`,
            bodyMarkdown: `${String(invocation.payload.bodyMarkdown)}\n\nVariante orientee angle complementaire pour reutilisation editoriale.`
          },
          hooks: [],
          variants: [
            {
              variantType: "repurpose",
              bodyMarkdown: `${String(invocation.payload.bodyMarkdown)}\n\nVariante orientee angle complementaire pour reutilisation editoriale.`
            }
          ],
          qualitySignals: {
            clarity: 0.8,
            specificity: 0.77,
            antiHypeAlignment: 0.95
          }
        }
      };
    case "linkedin-news-to-post":
      return {
        status: "succeeded",
        summary: "News transformed by Codex",
        data: {
          draft: {
            headline: String(invocation.payload.sourceTitle),
            bodyMarkdown: `${String(invocation.payload.sourceSummary)}\n\nAngle PME: prioriser les cas d'usage avant de courir apres la hype.`
          },
          hooks: [
            {
              family: "news-angle",
              text: "La news compte moins que la decision terrain qu'elle impose.",
              score: 0.81
            }
          ],
          variants: [],
          qualitySignals: {
            clarity: 0.82,
            specificity: 0.8,
            antiHypeAlignment: 0.95
          }
        }
      };
    case "linkedin-strategy-foundation": {
      const bundle = invocation.payload as {
        profile?: { name?: string; positioning?: string; bio?: string; expertiseSummary?: string };
        offers?: Array<{ name?: string; promise?: string }>;
        icps?: Array<{ segment?: string; pains?: string }>;
        pillars?: Array<{ label?: string; description?: string }>;
        voiceRules?: Array<{ ruleText?: string }>;
      } | null;
      const profileName = bundle?.profile?.name ?? "Auteur";
      const positioning = bundle?.profile?.positioning ?? "Positionnement non renseigne";
      const bio = bundle?.profile?.bio ?? "";
      const expertise = bundle?.profile?.expertiseSummary ?? "";
      const offersBlock = (bundle?.offers ?? [])
        .map((offer) => `- ${offer.name ?? "Offre"} : ${offer.promise ?? ""}`)
        .join("\n");
      const icpsBlock = (bundle?.icps ?? [])
        .map((icp) => `- ${icp.segment ?? "ICP"} : ${icp.pains ?? ""}`)
        .join("\n");
      const pillarsBlock = (bundle?.pillars ?? [])
        .map((pillar) => `- ${pillar.label ?? "Pilier"}`)
        .join("\n");
      const voiceBlock = (bundle?.voiceRules ?? [])
        .map((rule) => `- ${rule.ruleText ?? ""}`)
        .join("\n");
      return {
        status: "succeeded",
        summary: "Editorial foundation generated by Codex",
        data: {
          hooks: [],
          variants: [],
          qualitySignals: {
            clarity: 0.88,
            specificity: 0.84,
            antiHypeAlignment: 0.95
          }
        },
        artifacts: [
          {
            kind: "markdown",
            label: "editorial_foundation",
            content: [
              `# Socle editorial`,
              ``,
              `## Profil`,
              `Auteur : ${profileName}`,
              `Positionnement : ${positioning}`,
              bio ? `Bio : ${bio}` : "",
              expertise ? `Expertise : ${expertise}` : "",
              ``,
              offersBlock ? `## Offres\n${offersBlock}` : "",
              icpsBlock ? `## ICP\n${icpsBlock}` : "",
              pillarsBlock ? `## Piliers editoriaux\n${pillarsBlock}` : "",
              voiceBlock ? `## Regles de voix\n${voiceBlock}` : ""
            ]
              .filter((line) => line !== "")
              .join("\n")
          }
        ]
      };
    }
    case "linkedin-topic-generator":
      return {
        status: "succeeded",
        summary: "Topics generated by Codex",
        data: {
          hooks: [],
          variants: [],
          qualitySignals: {
            clarity: 0.82,
            specificity: 0.78,
            antiHypeAlignment: 0.95
          }
        },
        artifacts: [
          {
            kind: "markdown",
            label: "human_output",
            content: "1. Adoption IA - Pourquoi les prompts ne suffisent pas | angle: Le probleme est organisationnel | score: 0.82"
          }
        ]
      };
    default:
      return {
        status: "failed",
        summary: `Unknown skill: ${invocation.skillName}`,
        error: {
          code: "SKILL_NOT_FOUND",
          message: `No implementation for ${invocation.skillName}`
        }
      };
  }
}

export function createStrictSkillRunnerService() {
  return new SkillRunnerService({
    codexCliRunner: {
      isAvailable: () => true,
      execute: executeFakeCodex
    }
  });
}
