// Cross-domain identifier helper. The single source of truth for entity ids
// generated by the main process. Two modes:
//
//   1. Single argument (random hex variant) — used by every service that
//      needs a unique id without ordering guarantees:
//      `createId("draft")` → `draft_<timestamp>_<6-hex-chars>`
//
//   2. Two arguments (deterministic index variant) — used by the strategy
//      repository to generate ids that sort by their position in a list:
//      `createId("offer", 2)` → `offer_<timestamp>_2`
//
// The two modes intentionally produce different formats so they cannot collide
// at the suffix level even when generated within the same millisecond.

export function createId(prefix: string, index?: number): string {
  if (index === undefined) {
    return `${prefix}_${Date.now()}_${Math.random().toString(16).slice(2, 8)}`;
  }
  return `${prefix}_${Date.now()}_${index}`;
}
