import { afterEach, describe, expect, it, vi } from "vitest";
import {
  CodexCliRunner,
  type CodexCliCommandExecutor,
  type CodexCliFilesystem
} from "../../app/main/domains/execution/codex-cli-runner";
import type { SkillRunnerInvocation } from "../../app/main/domains/execution/skill-runner.service";

describe("codex cli runner", () => {
  const invocation: SkillRunnerInvocation = {
    runId: "run_1",
    skillName: "linkedin-post-writer",
    skillVersion: "1.0.0",
    context: {
      pillarLabel: "Adoption IA",
      voiceGuardrail: "Pas de hype, du terrain."
    },
    payload: {
      title: "Le vrai frein a l'IA en PME",
      angle: "Le probleme n'est presque jamais le prompt"
    },
    attachments: []
  };

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it("executes codex and parses the canonical JSON response", () => {
    const executor: CodexCliCommandExecutor = vi.fn().mockReturnValue({
      status: 0,
      stdout: "",
      stderr: ""
    });
    const filesystem: CodexCliFilesystem = {
      makeTempDir: vi.fn().mockReturnValue("/tmp/codex-runner"),
      readFile: vi.fn().mockReturnValue(
        JSON.stringify({
          status: "succeeded",
          summary: "Draft generated by Codex",
          data: {
            draft: {
              headline: "Le vrai frein a l'IA en PME",
              bodyMarkdown: "Texte"
            },
            hooks: [
              {
                family: "contrarian",
                text: "Hook",
                score: 0.9
              }
            ],
            variants: [],
            qualitySignals: {
              clarity: 0.9,
              specificity: 0.88,
              antiHypeAlignment: 0.95
            }
          }
        })
      ),
      removeDir: vi.fn()
    };
    const runner = new CodexCliRunner(executor, filesystem);

    const result = runner.execute(invocation);

    expect(result.status).toBe("succeeded");
    expect(result.summary).toContain("Codex");
    expect(executor).toHaveBeenCalled();
  });

  it("reports unavailable when codex execution fails", () => {
    const executor: CodexCliCommandExecutor = vi.fn().mockReturnValue({
      status: 1,
      stdout: "",
      stderr: "not logged in"
    });
    const filesystem: CodexCliFilesystem = {
      makeTempDir: vi.fn().mockReturnValue("/tmp/codex-runner"),
      readFile: vi.fn(),
      removeDir: vi.fn()
    };
    const runner = new CodexCliRunner(executor, filesystem);

    const result = runner.execute(invocation);

    expect(result.status).toBe("failed");
    expect(result.error?.code).toBe("CODEX_CLI_FAILED");
  });
});
