import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import {
  CodexCliRunner,
  resolveCodexCommand,
  type CodexCliCommandExecutor,
  type CodexCliFilesystem
} from "../../app/main/domains/execution/codex-cli-runner";
import {
  SkillPromptNotFoundError,
  createDefaultSkillPromptLoader,
  type SkillPromptLoader
} from "../../app/main/domains/execution/skill-prompt-loader";
import type { SkillRunnerInvocation } from "../../app/main/domains/execution/skill-runner.service";

describe("codex cli runner", () => {
  const invocation: SkillRunnerInvocation = {
    runId: "run_1",
    skillName: "linkedin-post-writer",
    skillVersion: "1.0.0",
    context: {
      pillarLabel: "Adoption IA",
      voiceGuardrail: "Pas de hype, du terrain."
    },
    payload: {
      title: "Le vrai frein a l'IA en PME",
      angle: "Le probleme n'est presque jamais le prompt"
    },
    attachments: []
  };

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it("executes codex and parses the canonical JSON response", () => {
    const executor: CodexCliCommandExecutor = vi.fn().mockReturnValue({
      status: 0,
      stdout: "",
      stderr: ""
    });
    const filesystem: CodexCliFilesystem = {
      makeTempDir: vi.fn().mockReturnValue("/tmp/codex-runner"),
      readFile: vi.fn().mockReturnValue(
        JSON.stringify({
          status: "succeeded",
          summary: "Draft generated by Codex",
          data: {
            draft: {
              headline: "Le vrai frein a l'IA en PME",
              bodyMarkdown: "Texte"
            },
            hooks: [
              {
                family: "contrarian",
                text: "Hook",
                score: 0.9
              }
            ],
            variants: [],
            qualitySignals: {
              clarity: 0.9,
              specificity: 0.88,
              antiHypeAlignment: 0.95
            }
          }
        })
      ),
      removeDir: vi.fn()
    };
    const runner = new CodexCliRunner(executor, filesystem);

    const result = runner.execute(invocation);

    expect(result.status).toBe("succeeded");
    expect(result.summary).toContain("Codex");
    expect(executor).toHaveBeenCalled();
    const prompt = (executor as ReturnType<typeof vi.fn>).mock.calls[0]?.[1] as string;
    expect(prompt).toContain("You are a premium LinkedIn editorial skill runner");
    expect(prompt).toContain("Do not expose internal labels");
    expect(prompt).toContain("Anti-hype");
    expect(prompt).toContain("French");
  });

  it("reports unavailable when codex execution fails", () => {
    const executor: CodexCliCommandExecutor = vi.fn().mockReturnValue({
      status: 1,
      stdout: "",
      stderr: "not logged in"
    });
    const filesystem: CodexCliFilesystem = {
      makeTempDir: vi.fn().mockReturnValue("/tmp/codex-runner"),
      readFile: vi.fn(),
      removeDir: vi.fn()
    };
    const runner = new CodexCliRunner(executor, filesystem);

    const result = runner.execute(invocation);

    expect(result.status).toBe("failed");
    expect(result.error?.code).toBe("CODEX_CLI_FAILED");
  });

  it("resolves the Codex command via the cross-platform helper without throwing", () => {
    // The helper returns either an absolute path (when a binary exists on the
    // host) or the bare "codex" fallback. Either outcome is acceptable for
    // this smoke test; the exact per-platform lookup behavior is exhaustively
    // covered by tests/unit/find-codex-binary.test.ts.
    const command = resolveCodexCommand();
    expect(typeof command).toBe("string");
    expect(command.length).toBeGreaterThan(0);
  });

  it("demands the exact structure-selector contract fields in the prompt", () => {
    const executor: CodexCliCommandExecutor = vi.fn().mockReturnValue({
      status: 1,
      stdout: "",
      stderr: "forced failure"
    });
    const filesystem: CodexCliFilesystem = {
      makeTempDir: vi.fn().mockReturnValue("/tmp/codex-runner"),
      readFile: vi.fn(),
      removeDir: vi.fn()
    };
    const runner = new CodexCliRunner(executor, filesystem);

    runner.execute({
      ...invocation,
      skillName: "linkedin-structure-selector"
    });

    const prompt = (executor as ReturnType<typeof vi.fn>).mock.calls[0]?.[1] as string;
    expect(prompt).toContain('Do not use "partial". If the contract cannot be fully satisfied, return "failed".');
    expect(prompt).toContain('"data": { "structures": [');
    expect(prompt).toContain('"qualitySignals": { "clarity": 0.0, "specificity": 0.0, "antiHypeAlignment": 0.0 }');
  });

  it("demands the exact strategy-foundation contract fields in the prompt", () => {
    const executor: CodexCliCommandExecutor = vi.fn().mockReturnValue({
      status: 1,
      stdout: "",
      stderr: "forced failure"
    });
    const filesystem: CodexCliFilesystem = {
      makeTempDir: vi.fn().mockReturnValue("/tmp/codex-runner"),
      readFile: vi.fn(),
      removeDir: vi.fn()
    };
    const runner = new CodexCliRunner(executor, filesystem);

    runner.execute({
      ...invocation,
      skillName: "linkedin-strategy-foundation"
    });

    const prompt = (executor as ReturnType<typeof vi.fn>).mock.calls[0]?.[1] as string;
    expect(prompt).toContain('Never place artifacts inside "data". Use the top-level "artifacts" array only.');
    expect(prompt).toContain('"artifacts": [{ "kind": "markdown", "label": "editorial_foundation", "content": "# ..." }]');
    expect(prompt).toContain('"error": null');
  });

  it("demands normalized hook scores and quality signals in the hook-engine prompt", () => {
    const executor: CodexCliCommandExecutor = vi.fn().mockReturnValue({
      status: 1,
      stdout: "",
      stderr: "forced failure"
    });
    const filesystem: CodexCliFilesystem = {
      makeTempDir: vi.fn().mockReturnValue("/tmp/codex-runner"),
      readFile: vi.fn(),
      removeDir: vi.fn()
    };
    const runner = new CodexCliRunner(executor, filesystem);

    runner.execute({
      ...invocation,
      skillName: "linkedin-hook-engine"
    });

    const prompt = (executor as ReturnType<typeof vi.fn>).mock.calls[0]?.[1] as string;
    expect(prompt).toContain('Return hook scores as decimals between 0 and 1. Never use percentages like 87 or 91.');
    expect(prompt).toContain('"hooks":[{"family":"...","text":"...","score":0.0}]');
    expect(prompt).toContain('"qualitySignals":{"clarity":0.0,"specificity":0.0,"antiHypeAlignment":0.0}');
    expect(prompt).toContain("Use these editorial references for sharpness, not for copy-paste");
    expect(prompt).toContain("La plupart des PME ne ratent pas l IA a cause des outils.");
    expect(prompt).toContain("Ban openings that are now too recognizable");
  });

  it("demands the publishable post-writer contract in the prompt", () => {
    const executor: CodexCliCommandExecutor = vi.fn().mockReturnValue({
      status: 1,
      stdout: "",
      stderr: "forced failure"
    });
    const filesystem: CodexCliFilesystem = {
      makeTempDir: vi.fn().mockReturnValue("/tmp/codex-runner"),
      readFile: vi.fn(),
      removeDir: vi.fn()
    };
    const runner = new CodexCliRunner(executor, filesystem);

    runner.execute({
      ...invocation,
      skillName: "linkedin-post-writer"
    });

    const prompt = (executor as ReturnType<typeof vi.fn>).mock.calls[0]?.[1] as string;
    expect(prompt).toContain('Return this exact success shape: {"status":"succeeded","summary":"...","data":{"draft":{"headline":"...","bodyMarkdown":"..."}');
    expect(prompt).toContain('"qualitySignals":{"clarity":0.0,"specificity":0.0,"antiHypeAlignment":0.0}');
    expect(prompt).toContain('If the draft is not publication-ready, return "failed" instead of a weak draft.');
    expect(prompt).toContain("The first two paragraphs must already contain a concrete business consequence or operational cost.");
    expect(prompt).toContain("Avoid generic openings such as 'On vend X comme l'etape d'apres'");
    expect(prompt).toContain("Use these editorial references for sharpness, not for copy-paste");
    expect(prompt).toContain("Une PME n a pas besoin de 20 cas d usage IA. Elle a besoin des 3 bons.");
    expect(prompt).toContain("Never open with formulas such as 'Le sujet n est pas...', 'Le debat n est pas...'");
  });

  it("demands a real editorial angle shift in the repurpose prompt", () => {
    const executor: CodexCliCommandExecutor = vi.fn().mockReturnValue({
      status: 1,
      stdout: "",
      stderr: "forced failure"
    });
    const filesystem: CodexCliFilesystem = {
      makeTempDir: vi.fn().mockReturnValue("/tmp/codex-runner"),
      readFile: vi.fn(),
      removeDir: vi.fn()
    };
    const runner = new CodexCliRunner(executor, filesystem);

    runner.execute({
      ...invocation,
      skillName: "linkedin-repurpose"
    });

    const prompt = (executor as ReturnType<typeof vi.fn>).mock.calls[0]?.[1] as string;
    expect(prompt).toContain("HARD CONSTRAINTS");
    expect(prompt).toContain("Different narrative structure");
    expect(prompt).toContain("Different hook family");
    expect(prompt).toContain("Different angle of attack");
    expect(prompt).toContain("NEVER reuse the source structure");
  });
});

describe("codex cli runner — timeout handling (FR-015, FR-016, FR-017)", () => {
  const baseInvocation: SkillRunnerInvocation = {
    runId: "run_timeout",
    skillName: "linkedin-post-writer",
    skillVersion: "1.0.0",
    context: {},
    payload: { title: "timeout test", angle: "timeout angle" },
    attachments: []
  };

  const baseFilesystem = (): CodexCliFilesystem => ({
    makeTempDir: vi.fn().mockReturnValue("/tmp/codex-timeout"),
    readFile: vi.fn().mockReturnValue(""),
    removeDir: vi.fn()
  });

  afterEach(() => {
    vi.restoreAllMocks();
    delete process.env.CODEX_CLI_TIMEOUT_MS;
  });

  it("emits CODEX_CLI_TIMEOUT when the synchronous child process is killed by the timeout option", () => {
    const executor: CodexCliCommandExecutor = vi.fn().mockReturnValue({
      status: null,
      signal: "SIGTERM",
      stdout: "",
      stderr: ""
    });
    const runner = new CodexCliRunner(executor, baseFilesystem());

    const result = runner.execute(baseInvocation);

    expect(result.status).toBe("failed");
    expect(result.error?.code).toBe("CODEX_CLI_TIMEOUT");
    expect(result.summary).toContain("timed out");
  });

  it("substitutes the effective CODEX_CLI_TIMEOUT_MS value into the error message", () => {
    process.env.CODEX_CLI_TIMEOUT_MS = "4500";
    const executor: CodexCliCommandExecutor = vi.fn().mockReturnValue({
      status: null,
      signal: "SIGTERM",
      stdout: "",
      stderr: ""
    });
    const runner = new CodexCliRunner(executor, baseFilesystem());

    const result = runner.execute(baseInvocation);

    expect(result.error?.message).toContain("4500");
  });

  it("falls back to the 120000 default when CODEX_CLI_TIMEOUT_MS is unset", () => {
    const executor: CodexCliCommandExecutor = vi.fn().mockReturnValue({
      status: null,
      signal: "SIGTERM",
      stdout: "",
      stderr: ""
    });
    const runner = new CodexCliRunner(executor, baseFilesystem());

    const result = runner.execute(baseInvocation);

    expect(result.error?.message).toContain("120000");
  });

  it("falls back to the default when CODEX_CLI_TIMEOUT_MS is not a positive integer", () => {
    process.env.CODEX_CLI_TIMEOUT_MS = "garbage";
    const executor: CodexCliCommandExecutor = vi.fn().mockReturnValue({
      status: null,
      signal: "SIGTERM",
      stdout: "",
      stderr: ""
    });
    const runner = new CodexCliRunner(executor, baseFilesystem());

    const result = runner.execute(baseInvocation);

    expect(result.error?.message).toContain("120000");
  });

  it("falls back to the default when CODEX_CLI_TIMEOUT_MS is zero or negative", () => {
    process.env.CODEX_CLI_TIMEOUT_MS = "-1";
    const executor: CodexCliCommandExecutor = vi.fn().mockReturnValue({
      status: null,
      signal: "SIGTERM",
      stdout: "",
      stderr: ""
    });
    const runner = new CodexCliRunner(executor, baseFilesystem());

    const result = runner.execute(baseInvocation);

    expect(result.error?.message).toContain("120000");
  });

  it("does NOT emit CODEX_CLI_TIMEOUT when status is non-zero but signal is not SIGTERM", () => {
    const executor: CodexCliCommandExecutor = vi.fn().mockReturnValue({
      status: 2,
      signal: null,
      stdout: "",
      stderr: "genuine failure"
    });
    const runner = new CodexCliRunner(executor, baseFilesystem());

    const result = runner.execute(baseInvocation);

    expect(result.status).toBe("failed");
    expect(result.error?.code).toBe("CODEX_CLI_FAILED");
  });

  it("allows a subsequent normal invocation to succeed after a timeout terminated the previous call", () => {
    let callCount = 0;
    const executor: CodexCliCommandExecutor = vi.fn().mockImplementation(() => {
      callCount += 1;
      if (callCount === 1) {
        return { status: null, signal: "SIGTERM", stdout: "", stderr: "" };
      }
      return { status: 0, stdout: "", stderr: "" };
    });
    const filesystem: CodexCliFilesystem = {
      makeTempDir: vi.fn().mockReturnValue("/tmp/codex-timeout-recovery"),
      readFile: vi.fn().mockReturnValue(
        JSON.stringify({
          status: "succeeded",
          summary: "Draft generated by Codex",
          data: {
            draft: { headline: "recovered", bodyMarkdown: "body" },
            hooks: [{ family: "contrarian", text: "h", score: 0.8 }],
            variants: [],
            qualitySignals: {
              clarity: 0.8,
              specificity: 0.8,
              antiHypeAlignment: 0.9
            }
          }
        })
      ),
      removeDir: vi.fn()
    };
    const runner = new CodexCliRunner(executor, filesystem);

    const firstResult = runner.execute(baseInvocation);
    expect(firstResult.error?.code).toBe("CODEX_CLI_TIMEOUT");

    const secondResult = runner.execute(baseInvocation);
    expect(secondResult.status).toBe("succeeded");
    expect(secondResult.error).toBeUndefined();
  });
});

describe("codex cli runner — SKILL.md integration (feature 006)", () => {
  const baseInvocation: SkillRunnerInvocation = {
    runId: "run_skillmd",
    skillName: "linkedin-post-writer",
    skillVersion: "1.0.0",
    context: {},
    payload: { title: "test", angle: "test" },
    attachments: []
  };

  it("returns SKILL_PROMPT_NOT_FOUND when the loader throws", () => {
    const stubLoader: SkillPromptLoader = {
      loadPrompt(skillName: string): string {
        throw new SkillPromptNotFoundError(skillName, `prompt missing for ${skillName}`);
      }
    };
    const executor: CodexCliCommandExecutor = vi.fn().mockReturnValue({
      status: 0,
      stdout: "",
      stderr: ""
    });
    const filesystem: CodexCliFilesystem = {
      makeTempDir: vi.fn().mockReturnValue("/tmp/codex-skillmd-test"),
      readFile: vi.fn().mockReturnValue(""),
      removeDir: vi.fn()
    };
    const runner = new CodexCliRunner(executor, filesystem, stubLoader);

    const result = runner.execute(baseInvocation);

    expect(result.status).toBe("failed");
    expect(result.error?.code).toBe("SKILL_PROMPT_NOT_FOUND");
    expect(result.error?.message).toContain("linkedin-post-writer");
    expect(executor).not.toHaveBeenCalled();
    expect(filesystem.makeTempDir).not.toHaveBeenCalled();
  });

  it("respects edited SKILL.md content on the next invocation (no cache)", () => {
    const tmpRoot = mkdtempSync(join(tmpdir(), "linkedin-poster-runner-edit-"));
    try {
      mkdirSync(join(tmpRoot, "linkedin-post-writer"), { recursive: true });
      const skillFile = join(tmpRoot, "linkedin-post-writer", "SKILL.md");

      const promptV1 = "FIRST PROMPT BODY MARKER";
      const promptV2 = "SECOND PROMPT BODY MARKER";

      writeFileSync(skillFile, `# linkedin-post-writer\n\n## Prompt\n\n${promptV1}\n`, "utf-8");

      const capturedPrompts: string[] = [];
      const executor: CodexCliCommandExecutor = vi.fn().mockImplementation((_args, input) => {
        capturedPrompts.push(input);
        return { status: 0, stdout: "", stderr: "" };
      });
      const filesystem: CodexCliFilesystem = {
        makeTempDir: vi.fn().mockReturnValue("/tmp/codex-edit-test"),
        readFile: vi
          .fn()
          .mockReturnValue(JSON.stringify({ status: "succeeded", summary: "ok", data: {} })),
        removeDir: vi.fn()
      };
      const loader = createDefaultSkillPromptLoader(tmpRoot);
      const runner = new CodexCliRunner(executor, filesystem, loader);

      runner.execute(baseInvocation);
      writeFileSync(skillFile, `# linkedin-post-writer\n\n## Prompt\n\n${promptV2}\n`, "utf-8");
      runner.execute(baseInvocation);

      expect(capturedPrompts).toHaveLength(2);
      expect(capturedPrompts[0]).toContain(promptV1);
      expect(capturedPrompts[0]).not.toContain(promptV2);
      expect(capturedPrompts[1]).toContain(promptV2);
      expect(capturedPrompts[1]).not.toContain(promptV1);
    } finally {
      rmSync(tmpRoot, { recursive: true, force: true });
    }
  });
});
