import { describe, expect, it } from "vitest";
import {
  SkillRunnerService,
  type SkillRunnerResult
} from "../../app/main/domains/execution/skill-runner.service";

describe("skill runner service", () => {
  const service = new SkillRunnerService();

  it("returns canonical JSON output for linkedin-post-writer", async () => {
    const result = await service.execute({
      runId: "run_1",
      skillName: "linkedin-post-writer",
      skillVersion: "1.0.0",
      context: {
        profileId: "profile_active",
        pillarLabel: "Adoption IA",
        voiceGuardrail: "Pas de hype, du terrain."
      },
      payload: {
        ideaId: "idea_1",
        title: "Le vrai frein a l'IA en PME",
        angle: "Le probleme n'est presque jamais le prompt"
      },
      attachments: []
    });

    expect(result.status).toBe("succeeded");
    expect(result.data?.draft?.headline).toContain("Le vrai frein");
    expect(result.data?.hooks.length).toBeGreaterThan(0);
    expect(result.data?.qualitySignals.antiHypeAlignment).toBeGreaterThan(0.8);
  });

  it("returns a failed contract for an unknown skill", async () => {
    const result = await service.execute({
      runId: "run_2",
      skillName: "unknown-skill",
      skillVersion: "1.0.0",
      context: {},
      payload: {},
      attachments: []
    });

    expect(result.status).toBe("failed");
    expect(result.error?.code).toBe("SKILL_NOT_FOUND");
    expect(result.summary).toContain("Unknown skill");
  });

  it("returns a variant payload for linkedin-repurpose", async () => {
    const result = await service.execute({
      runId: "run_3",
      skillName: "linkedin-repurpose",
      skillVersion: "1.0.0",
      context: {
        pillarLabel: "Methodes",
        voiceGuardrail: "Pas de hype, du terrain."
      },
      payload: {
        headline: "Pourquoi cadrer avant de prompter",
        bodyMarkdown: "Le process prime sur l'outil."
      },
      attachments: []
    });

    expect(result.status).toBe("succeeded");
    expect(result.data?.variants).toHaveLength(1);
    expect(result.data?.variants[0]?.variantType).toBe("repurpose");
  });

  it("returns draft content from linkedin-news-to-post", async () => {
    const result = await service.execute({
      runId: "run_4",
      skillName: "linkedin-news-to-post",
      skillVersion: "1.0.0",
      context: {
        pillarLabel: "Veille",
        voiceGuardrail: "Pas de hype, du terrain."
      },
      payload: {
        sourceTitle: "Une PME industrialise ses copilotes IA",
        sourceSummary: "Le sujet central est l'adoption terrain et la priorisation des cas d'usage."
      },
      attachments: []
    });

    expect(result.status).toBe("succeeded");
    expect(result.data?.draft?.headline).toContain("copilotes IA");
    expect(result.summary).toContain("News transformed");
  });

  it("returns a structured foundation summary for linkedin-strategy-foundation", async () => {
    const result = await service.execute({
      runId: "run_4b",
      skillName: "linkedin-strategy-foundation",
      skillVersion: "1.0.0",
      context: {},
      payload: {
        profile: {
          name: "Philippe",
          positioning: "Consultant IA PME"
        },
        offers: [{ name: "Offre coeur" }],
        icps: [{ segment: "Dirigeants PME" }],
        pillars: [{ label: "Adoption IA" }],
        voiceRules: [{ ruleText: "Pas de hype" }]
      },
      attachments: []
    });

    expect(result.status).toBe("succeeded");
    expect(result.summary).toContain("Strategy foundation");
    expect(result.artifacts?.[0]?.content).toContain("Consultant IA PME");
  });

  it("returns scored ideas for linkedin-topic-generator", async () => {
    const result = await service.execute({
      runId: "run_4c",
      skillName: "linkedin-topic-generator",
      skillVersion: "1.0.0",
      context: {},
      payload: {
        profileName: "Philippe",
        positioning: "Consultant IA PME",
        pillars: [{ label: "Adoption IA" }, { label: "ROI" }],
        icps: [{ segment: "Dirigeants PME" }],
        offers: [{ name: "Offre coeur" }]
      },
      attachments: []
    });

    expect(result.status).toBe("succeeded");
    expect(result.summary).toContain("Topics generated");
    expect(result.artifacts?.[0]?.content).toContain("Adoption IA");
  });

  it("prefers codex cli when available", async () => {
    const service = new SkillRunnerService({
      codexCliRunner: {
        isAvailable: () => true,
        execute: () =>
          ({
            status: "succeeded",
            summary: "Generated by Codex CLI",
            data: {
              draft: {
                headline: "Titre",
                bodyMarkdown: "Texte"
              },
              hooks: [],
              variants: [],
              qualitySignals: {
                clarity: 0.9,
                specificity: 0.9,
                antiHypeAlignment: 0.95
              }
            }
          }) as SkillRunnerResult
      }
    });

    const result = await service.execute({
      runId: "run_5",
      skillName: "linkedin-post-writer",
      skillVersion: "1.0.0",
      context: {},
      payload: {},
      attachments: []
    });

    expect(result.summary).toContain("Codex CLI");
  });
});
